#!/usr/bin/expect -f

set prompt "Agent registered"
set address "00:90:E1:FF:99:DF"
spawn sudo bluetoothctl
expect -exact $prompt
send -- "trust $address\r"
expect -exact "#"

set connected "false"
while {$connected == "false"} {
    send -- "connect $address\r"
    sleep 1
    send -- "info $address\r"
    expect {
        "*Connected: yes*" {set connected "true"}
    }
}
send -- "quit\r"
expect eof
