#!/bin/bash

cd ../pixy2/scripts
./build_libpixyusb2.sh
rm /usr/include/pixy2 -r
mkdir /usr/include/pixy2/host/libpixyusb2/include -p
mkdir /usr/include/pixy2/host/arduino/libraries/Pixy2 -p
mkdir /usr/include/pixy2/common/inc -p
cd -
cp ../pixy2/src/host/libpixyusb2/include/*.h /usr/include/pixy2/host/libpixyusb2/include
cp ../pixy2/src/host/arduino/libraries/Pixy2/*.h /usr/include/pixy2/host/arduino/libraries/Pixy2
cp ../pixy2/src/common/inc/*.h /usr/include/pixy2/common/inc
cp ../pixy2/src/common/inc/*.hpp /usr/include/pixy2/common/inc
cp ../pixy2/build/libpixyusb2/libpixy2.a /usr/lib
